### ISSUE TITLE
How to stop FOUC from happening with native Web Components

### ISSUE THREAD

**Issue by danieldietrich** [danieldietrich/candid#19]
## Using an app-content wrapper

```html
<body>
  <!-- best practice: use a web component as root for the content in order to reduce FOUC -->
  <!-- also: don't use slots to prevent FOUC -->
  <app-content></app-content>
  <!-- the template content is processed before connecting it to the live DOM -->
  <script type="module">
    import candid from "./src/index.js";
    window.addEventListener('load', () => candid());
  </script>
</body>
```

## Pre-styling unregistered elements

Before an element is [upgraded](https://developers.google.com/web/fundamentals/web-components/customelements#upgrades) you can target it in CSS using the :defined pseudo-class. This is useful for pre-styling a component. For example, you may wish to prevent layout or other visual FOUC by hiding undefined components and fading them in when they become defined.

**Note:** this does not help for customized built-in elements `<div is="ext-div">Loading...</div>`

**Example:** hide `<app-drawer>` before it's defined:

```css
app-drawer:not(:defined) {
  /* Pre-style, give layout, replicate app-drawer's eventual styles, etc. */
  display: inline-block;
  height: 100vh;
  opacity: 0;
  transition: opacity 0.3s ease-in-out;
}
```

After `<app-drawer>` becomes defined, the selector (`app-drawer:not(:defined)`) no longer matches.

Source: [google web fundamentals](https://developers.google.com/web/fundamentals/web-components/customelements#prestyle)

See also https://stackoverflow.com/questions/62683430/how-to-stop-fouc-from-happening-with-native-web-components
